@NextcloudWebdavApi_HostAddress = http://localhost:5125

POST {{NextcloudWebdavApi_HostAddress}}/files
Content-Type: application/json

{
  "Path": "foo.txt",
  "Content": "barbla"
}

###

GET {{NextcloudWebdavApi_HostAddress}}/files
Content-Type: application/json

{
  "Path": "foo.txt"
}

###