name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false

      - name: Extract tag name
        id: extract_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        if: github.event_name == 'create'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        uses: docker/build-push-action@v2
        if: github.event_name == 'create'
        with:
          context: .
          push: true
          tags: ghcr.io/phoenox/nextcloud-webdav-api:${{ steps.extract_tag.outputs.tag }}
